### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by ModuLIZER** [drone076/vue2-ckeditor5#1]
Hi, I have a issue where I keep getting:
```
TypeError: Cannot read property 'on' of undefined
    at eval (Ckeditor.vue?77a5:34)
```
refering to this line: ```editor.document.on('changesDone', (evt, data) => {``` where editor.document is undefined.

I have followed your example and use following CKeditor.vue file:
```
<template>
    <textarea id="editor" :value="value"
        v-on:input="updateValue($event.target.value)" >
    </textarea>
</template>

<script>
import ClassicEditor from '@ckeditor/ckeditor5-build-classic'

export default {
  name: 'ckeditor',
  data: function () {
    return {
      instance: null
    }
  },
  props: ['value'],
  watch: {
    value () {
      let html = this.instance.getData()
      if (html !== this.value) {
        this.instance.setData(this.value)
      }
    }
  },
  mounted () {
    ClassicEditor
      .create(this.$el, {
        toolbar: ["bold", "italic", "link", "bulletedList", "numberedList"]
      })
      .then(editor => {
        this.instance = editor;
        editor.document.on('changesDone', (evt, data) => {
          this.updateValue(editor.getData())
        })
      })
      .catch(error => {
        console.error(error);
      })
  },
  methods: {
    updateValue: function (value) {
      this.$emit('input', value)
    }
  }
}
</script>
```
And I use it like this:
```
<template>
  <div class="new-post">
        <ckeditor v-model="newPost.content"></ckeditor>
  </div>
</template>

<script>
  import Ckeditor from './../shared/Ckeditor'
  export default {
    data: function () {
      return {
        newPost: { content: "This is some content" }
    }
    components: {
      Ckeditor
    },
  }
```

I do get the editor and the content is correctly shown "This is some content" but the editor does not update the value.

Using:
@ckeditor/ckeditor5-build-classic@1.0.0-beta.1
vue@2.5.16

Do have any idear to what goes wrong here?

**Comment by diemah77** [comment]
There is no `changesDone` event anymore. Replace `changesDone` by `change`.

**Comment by diemah77** [comment]
The document property has been wrapped into model property of the Editor object. So replace this

`` editor.document.on('changesDone', (evt, data) => {
          this.updateValue(editor.getData())
        })``

by that

`` editor.model.document.on(change, () => {
          this.updateValue(editor.getData())
        })
``

**Comment by ModuLIZER** [comment]
Nice one... Changed to tinyMCE though as CKEditor was a real pain to work with compined with webpack.
